In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])

In [5]:
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [6]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [7]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [10]:
model.get_weights()

[array([[-0.85167855,  1.1152068 ],
        [ 0.91690147,  0.24664903]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.85476875],
        [ 0.7315446 ]], dtype=float32),
 array([0.], dtype=float32)]

In [12]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [14]:
model.set_weights(new_weights)

In [15]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [16]:
optimizer =  keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [17]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 [==============================] - 1s 3ms/step - loss: 27.8961
Epoch 2/75
4/4 [==============================] - 0s 5ms/step - loss: 27.5937
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 27.2442
Epoch 4/75
4/4 [==============================] - 0s 5ms/step - loss: 26.9248
Epoch 5/75
4/4 [==============================] - 0s 2ms/step - loss: 26.5767
Epoch 6/75
4/4 [==============================] - 0s 5ms/step - loss: 26.2185
Epoch 7/75
4/4 [==============================] - 0s 4ms/step - loss: 25.8496
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 25.4681
Epoch 9/75
4/4 [==============================] - 0s 3ms/step - loss: 25.0581
Epoch 10/75
4/4 [==============================] - 0s 8ms/step - loss: 24.6512
Epoch 11/75
4/4 [==============================] - 0s 5ms/step - loss: 24.2582
Epoch 12/75
4/4 [==============================] - 0s 3ms/step - loss: 23.8464
Epoch 13/75
4/4 [==============================] - 0s 4ms/ste

In [18]:
model.get_weights()

[array([[0.37387073, 0.37387073],
        [0.36561698, 0.36561698]], dtype=float32),
 array([0.2724311, 0.2724311], dtype=float32),
 array([[0.37302735],
        [0.37302735]], dtype=float32),
 array([0.20472449], dtype=float32)]